### ISSUE TITLE
命令行无法编译，IDE 打开目录时行为不符合预期

### ISSUE THREAD

**Issue by BewareMyPower** [nuoyimanaituling/xzwrpc#1]
系统：MacOS

进入 v3 分支的 xzwrpc 目录，运行：

```bash
mvn clean package
```

> [ERROR] Failed to execute goal org.apache.maven.plugins:maven-compiler-plugin:3.1:compile (default-compile) on project rpc-core: Compilation failure
> [ERROR] xzwrpc/xzwrpc/rpc-core/src/main/java/io/xzw/xzwrpc/stub/net/NetConstant.java:[4,50] 程序包com.sun.xml.internal.ws.policy.privateutil不存在

Intellij Idea 打开项目目录时：

![image](https://user-images.githubusercontent.com/18204803/125155053-fdd37a00-e18f-11eb-8186-b37e5002bf9b.png)

点击 Open 后加载的只有 rpc-test 模块：

![image](https://user-images.githubusercontent.com/18204803/125155068-19d71b80-e190-11eb-8860-812d313de0eb.png)

需要显式地打开 rpc-core 目录

----

其他相对小的问题：
- git 上传请使用 .gitignore 文件忽略掉 Maven 编译的中间文件以及 IDE 相关的文件，参考：https://github.com/apache/pulsar/blob/master/.gitignore
- 对于开源项目，文档非常重要，参考 https://github.com/apache/pulsar#build-pulsar
- 测试同样重要，请使用 JUnit 或者 TestNG 进行自动化测试，而不是用打印标准输出的方式在本地进行人工测试，对于 RPC，可以参考 https://github.com/sofastack/sofa-rpc/tree/master/test
- 请使用 maven-checkstyle-plugin 或其他方法约束代码风格

**Comment by nuoyimanaituling** [comment]
嗯嗯，谢谢您的建议，我会马上改正并修正规范

**Comment by nuoyimanaituling** [comment]
解决了编译问题，原因是因为使用到了jdk内部接口，但是没有动态指向开发者本机所在的JDK 路径，已经改正

**Comment by nuoyimanaituling** [comment]
谢谢您，我会继续加油的
